version: "3.9"

services:
  smart-mirror-mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" # to prevent conflict with a local mongodb
    networks:
      - smart-mirror-net

  smart-mirror-api:
    image: mohamedfouad71/smart-mirror-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - smart-mirror-mongo
    networks:
      - smart-mirror-net
  smart-mirror-dashboard:
    image: mohamedfouad71/smart-mirror-dashboard:latest
    ports:
      - "8081:80"
    networks:
      - smart-mirror-net

networks:
  smart-mirror-net:
    driver: bridge
